- name: Copy systemd service file
  template:
    src: streamlit.service.j2
    dest: /etc/systemd/system/streamlit.service
    mode: '0644'

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start streamlit service
  systemd:
    name: streamlit
    enabled: yes
    state: started
